# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PaginationDummy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PaginationDummy
  pod 'SDWebImage'
  pod 'Alamofire'
  pod 'PaginatedTableView'   

  target 'PaginationDummyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PaginationDummyUITests' do
    # Pods for testing
  end

end
